### ISSUE TITLE
Merge with the Powerline project?

### ISSUE THREAD

**Issue by s0r00t** [darac/irssi-powerline#3]
https://powerline.readthedocs.org/en/master/

This would allow easier installation, with other Powerline projects. 
Also, this would gather all the Powerline 'themes' together.

**Comment by her** [comment]
Yes, I agree. Bundling them together would be smart.

**Comment by darac** [comment]
I think, for proper integration with powerline, this should use the full powerline system, rather than just being a "powerline-like skin".

As I understand it, I could use powerline to replace adv_windowlist.pl. Powerline seems to work like this:

 * The Window List becomes a call to powerline saying "render me a list of current windows".
 * Powerline then queries IRSSI for the raw data (what windows are visible, what windows are focussed etc) and produces the "power line" - nicely picking the colours of the chevrons so that you don't need the gaps between segments etc. Powerline also takes into account the theming, whether the user wants to use chevrons or whether they want to fall back to ">" etc.
 * Once the line is built, it is passed back to the querying plugin, which translates that into "IRSSI drawing" calls.

I think I'm going to call this "wontfix", as I think moving to weechat for this might be easier. :)
